name: Build

on: push

jobs:
  build:
    runs-on: Manjaro-20.2.1

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{cpp,h} | xargs clang-format -i && git diff --exit-code

      - name: Build application
        run: make   